controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    diff_cont:
      type: diff_drive_controller/DiffDriveController

# Publish all joint states -----------------------------------
joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100

joint_velocity_controller:
  ros__parameters:
    joints:
      - vesc_joint
    publish_rate: 100

diff_cont:
  ros__parameters:
    publish_rate: 100.0
    left_wheel_names: ['vesc_joint']
    right_wheel_names: ['vesc_joint_right']
    wheel_separation: 0.35
    wheel_radius: 0.05
    use_stamped_vel: false
